### ISSUE TITLE
API Portal failed on certificate mount

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#26]
It looks like the api portal container is now referencing a wrong secret mount ... shouldn't this be `apiportal-certs` instead?
![Screenshot from 2022-02-22 14-29-26](https://user-images.githubusercontent.com/969476/155132990-4abcf2bd-0949-4077-a815-4753caa6e543.png)

**Comment by cwiechmann** [comment]
Thanks for reporting. Yes, it should be `apiportal-certs`. I checked the configuration and it looks fine. It's even hardcoded in `apiportal-deployment.yaml`:
```
      {{- if .Values.apiportal.persistence.enabled }}
        - name: enckey
          persistentVolumeClaim:
            claimName: apiportal-enckey
        - name: images
          persistentVolumeClaim:
            claimName: apiportal-images
        - name: language
          persistentVolumeClaim:
            claimName: apiportal-language
        - name: templates
          persistentVolumeClaim:
            claimName: apiportal-templates
        - name: admlanguage
          persistentVolumeClaim:
            claimName: apiportal-adm-language
        - name: certs
          persistentVolumeClaim:
            claimName: apiportal-certs
      {{- end }}
```
This is the actual version of the HELM-Chart. Which version are you trying to deploy?
