### ISSUE TITLE
Broken template for external

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#35]
Using `CASS_PASS` with existing secret breaks both apimgr and apitraffic

```
- name: CASS_PASS
        {{- if .Values.cassandra.dbUser.existingSecret }}
{{ toYaml .Values.cassandra.dbUser.existingSecret | indent 10 }}
```

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @dokuboyejo. The documentation in the values.yaml and the actual implementation in the templates are totally wrong.

Now, the templates for apimgr and apitraffic are generating a proper secret reference out of the given secret name. For example:

```yaml
        - name: CASS_PASS
          valueFrom:
            secretKeyRef:
              name: "an-existing-secret"
              key: cassandra-password
```
