### ISSUE TITLE
Error connecting to external Cassandra cluster with racks

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#36]
When using 3-nodes external Cassandra, specifying one of the cluster seed ip in the nameOverride does't work

```
cassandra:
  # Set to false, to use an existing (external) Cassandra-DB
  internal: false

  # Only a subset of possible parameters is mentioned here. You can review and use all configuration values
  # as documented here:
  # https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values.yaml

#  nameOverride: "cassandra"
  nameOverride: "X.X.X.X"
  fullnameOverride: "cassandra"
```

Is there a standard way of connecting to external Cassandra cluster?
