### ISSUE TITLE
Add support for topologySpreadConstraint

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#37]
Thanks for the recent support of ``podAntiAffinity``.

While the addition of `podAntiAffinity` is great, If you also check these [proposals](https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/895-pod-topology-spread#proposal) as well as corresponding [motivations](https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/895-pod-topology-spread#motivation), it seems the sig team favors the usage of `pod.spec.topologySpreadConstraint`  over `pod.spec.affinity.podAntiAffinity` especially in situation where `RollingUpdate` or `vertical scaling` is required.

**Comment by cwiechmann** [comment]
Would you also recommend, not only to add support for this, but also make this the default instead of podAntiAffinity  ?

**Comment by dokuboyejo** [comment]
@cwiechmann  I suppose making `topologySpreadConstraint` the default would align with the [sigs proposal](https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/895-pod-topology-spread#proposal) as well, while still supporting `podAntiAffinity`

**Comment by cwiechmann** [comment]
That would be my proposal as the default configuration for the API-Traffic PODs.

```yaml
   topologySpreadConstraints: 
      # Avoid scheduling of API-Gateways in the same availability zone
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: traffic
      # Avoid scheduling of API-Gateways on the same node
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
           matchLabels:
            app.kubernetes.io/name: traffic
```

Any comments from your side @dokuboyejo?
