### ISSUE TITLE
Unable to see api metrics in api manager

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#52]
**Describe the bug**
Metrics in API Manager aren't accessible.
Severity of the problem [CRITICAL]

**To Reproduce**
1. Helm template/update/install '....' -f value.yaml
2. Access the api manager
![Screenshot from 2022-09-19 11-13-20](https://user-images.githubusercontent.com/969476/190986874-8cbe435e-690c-4cfe-912f-19552a983675.png)

**Expected behavior**
Similar to the view in node manager, we need to be able to see the metrics in api manager. The node manager allows metrics up-to 5days, whereas, the api manager can allow custom date to be provided, which is the main need here
![Screenshot from 2022-09-19 11-17-43](https://user-images.githubusercontent.com/969476/190986912-d6995951-ddf6-45d1-a3c1-89fee5727215.png)

**Technical context(please complete the following information):**
 - Helmchart version: 2.10.1
 - Kubernetes version: v1.23.0
 - Kubernetes distribution: EKS

**Comment by NComandini** [comment]
Hello @dokuboyejo, Could you show me the environment variable for api-manager component please ? Are you using the mysql component ?

**Comment by dokuboyejo** [comment]
@NComandini  it looks like below

```
externalMetricsDB:
  env:
    - name: METRICS_DB_URL
      value: "jdbc:mysql://<host>:3306/metrics?useSSL=false"
    - name: METRICS_DB_USERNAME
      value: "...."
    - name: METRICS_DB_PASS
      valueFrom:
        secretKeyRef:
          name: "...."
          key: "...."
```
